### ISSUE TITLE
alsa simple sound card & mdm9607 i2s

### ISSUE THREAD

**Issue by nikitos1550** [Biktorgj/quectel_eg25_kernel#6]
Hello!

Is it possible to setup alsa generic simple sound card driver to work with qcom,msm-dai-mi2s driver instead of using qcom provided complicated sound card driver?
Looking for help and advices.

**Comment by Biktorgj** [comment]
Depends on what you need.

If it's just for audio playback and recording (outside of call functionality), then sure, you can use ALSA UCM, alsamixer etc. without issues. If you want to handle call support you'll need to know _when_ a call is taking place, and that can only be done by actively querying the modem, or sniffing messages going between it and its host. 

Audo controls for the modem can only be enabled whenever there's a call, and only the particular controls for that type of call can be enabled (for example, the controls for VoLTE calls are different of those for circuit switch calls).

On stock firmware, there's a daemon from quectel that listens to call events, and then uses an alsa library to set up the correct paths. In the opensource firmware, that's handled by Openqti in a much simpler way (just listen for events and setup mixers accordingly)

Note that Quectel's kernel sources are fully of tremendously ugly hacks (and mine has one or two too) to account for diffrerent codec configurations that need to be taken care of too (in the opensource firmware only the RT5616 is supported but quectel has  3-4 different analog codecs)

**Comment by nikitos1550** [comment]
Yes, I want use audio completely outside call functionality.
I tried tune simple sound driver

```
    sound_simple {
        compatible = "simple-audio-card";
        simple-audio-card,format = "i2s";
        simple-audio-card,name = "simple";
        //simple-audio-card,mclk-fs = <64>;
        //simple-audio-card,widgets =
        //  "Microphone", "Microphone Jack",
        //  "Headphone", "Headphone Jack";
        //simple-audio-card,routing =
        //  "MIC1", "Microphone Jack",
        //  "MIC2", "Microphone Jack",
        //  "Microphone Jack", "micbias1",
        //  "Headphone Jack", "HPOL",
        //  "Headphone Jack", "HPOR";

        simple-audio-card,cpu {
            sound-dai = <&mi2s_sec>;
        };
        simple-audio-card,codec {
            //sound-dai = <&rt5616_codec>;
            sound-dai = <&alc5616_codec>;
        };
    };

```

But this is not working, because DAIs that sould be provided by mi2s_sec is not registered, even after modem dsp fw is loaded, it doesn't appear. Seems original qualcomm sound card driver `qcom,mdm9607-audio-tomtom` somehow init everything related.

Do you have any ideas how to avoid qualcomm sound card driver and use simple one instead? Or should I forget about this idea and ho with original qcom drv?

> Depends on what you need.
> 
> If it's just for audio playback and recording (outside of call functionality), then sure, you can use ALSA UCM, alsamixer etc. without issues. If you want to handle call support you'll need to know _when_ a call is taking place, and that can only be done by actively querying the modem, or sniffing messages going between it and its host.
> 
> Audo controls for the modem can only be enabled whenever there's a call, and only the particular controls for that type of call can be enabled (for example, the controls for VoLTE calls are different of those for circuit switch calls).
> 
> On stock firmware, there's a daemon from quectel that listens to call events, and then uses an alsa library to set up the correct paths. In the opensource firmware, that's handled by Openqti in a much simpler way (just listen for events and setup mixers accordingly)
> 
> Note that Quectel's kernel sources are fully of tremendously ugly hacks (and mine has one or two too) to account for diffrerent codec configurations that need to be taken care of too (in the opensource firmware only the RT5616 is supported but quectel has 3-4 different analog codecs)

**Comment by Biktorgj** [comment]
DAIs won't show up because they depend on Qualcomm's audio stack, so the simple-card driver can't handle them. You might be able to trim down mdm9607 sound driver so it's not that big, but I don't think it's worth the trouble. 
If you only need HiFi playback/capture, you just need to enable the correct mixer and set the sampling rate accordingly, no need to fight the kernel (https://github.com/the-modem-distro/meta-qcom/blob/c47b79122f70022a87fb30615d9dd649645e6faf/recipes-modem/openqti/files/src/audio.c#L138)

You can do it directly by interacting with ALSA via ioctls, or you can use alsaucm and some profiles (https://github.com/the-modem-distro/meta-qcom/blob/hardknott/recipes-proprietary/quectel-configs/files/etc/snd_soc_msm/snd_soc_msm_I2S)

**Comment by nikitos1550** [comment]
> DAIs won't show up because they depend on Qualcomm's audio stack, so the simple-card driver can't handle them. You might be able to trim down mdm9607 sound driver so it's not that big, but I don't think it's worth the trouble. If you only need HiFi playback/capture, you just need to enable the correct mixer and set the sampling rate accordingly, no need to fight the kernel (https://github.com/the-modem-distro/meta-qcom/blob/c47b79122f70022a87fb30615d9dd649645e6faf/recipes-modem/openqti/files/src/audio.c#L138)
> 
> You can do it directly by interacting with ALSA via ioctls, or you can use alsaucm and some profiles (https://github.com/the-modem-distro/meta-qcom/blob/hardknott/recipes-proprietary/quectel-configs/files/etc/snd_soc_msm/snd_soc_msm_I2S)

Thanks, let me learn it first.

**Comment by nikitos1550** [comment]
> DAIs won't show up because they depend on Qualcomm's audio stack, so the simple-card driver can't handle them. You might be able to trim down mdm9607 sound driver so it's not that big, but I don't think it's worth the trouble. If you only need HiFi playback/capture, you just need to enable the correct mixer and set the sampling rate accordingly, no need to fight the kernel (https://github.com/the-modem-distro/meta-qcom/blob/c47b79122f70022a87fb30615d9dd649645e6faf/recipes-modem/openqti/files/src/audio.c#L138)
> 
> You can do it directly by interacting with ALSA via ioctls, or you can use alsaucm and some profiles (https://github.com/the-modem-distro/meta-qcom/blob/hardknott/recipes-proprietary/quectel-configs/files/etc/snd_soc_msm/snd_soc_msm_I2S)

Is this tuned for quectel kernel (with sound card driver custom patches) or should work even on qualcomm open source driver version?

**Comment by nikitos1550** [comment]
FInally I managed rt5616 output sound via secondary i2s. thanks.
